### ISSUE TITLE
Shortcuts not working?

### ISSUE THREAD

**Issue by andrew121410** [justcla/KeyBindings#22]
When importing a shortcut from Tools -> Keyboard Shortcuts -> Load Shortcuts nothing is being added to the keyboard mapping scheme. 

![image](https://user-images.githubusercontent.com/12376951/191868850-ba578d65-b675-4f3d-adba-3432f2db2771.png)

![image](https://user-images.githubusercontent.com/12376951/191868664-840c63d2-e59e-4a45-8b94-7de7cc3afbb4.png)

![image](https://user-images.githubusercontent.com/12376951/191868707-ac40821a-6d3b-429e-b57d-c341ccfefabb.png)

Or
![image](https://user-images.githubusercontent.com/12376951/191868937-bbde50bc-1394-4fb6-a28e-bfea570c5f10.png)

![image](https://user-images.githubusercontent.com/12376951/191868409-8ef74eac-39fc-4db2-b081-971ed6b63448.png)

**Comment by justcla** [comment]
Well, that is by design.
There are two options for changing shortcuts.
1. You can turn on a mapping scheme, which brings in all the shortcuts in that scheme.
2. You can "import" specific shortcuts (without a mapping scheme) and these shortcuts will exist no matter what mapping scheme is applied.

I have found option 2 to be the most reliable, because a mapping scheme will not always override manually created shortcuts, so you might not get the correct experience.

So when you "Load Shortcuts", it has nothing to do with mapping schemes. It just adds (or removes) individual shortcuts.

When you saw the dialog that said "Keyboard shortcuts successfully imported!", it meant they are now available.
Just try using the shortcuts and you should see that they work - because you have imported them.

Forget about the mapping schemes. :-)

**Comment by andrew121410** [comment]
Oh it does work lol. I was trying to do CTRL + Alt + O to clean the imports and CTRL + Alt + L to reformat code, but that doesn't seem to work. But the reset of the keys that I need work.

**Comment by justcla** [comment]
(ahem) *coughs quietly*
Um....You're welcome?

**Comment by andrew121410** [comment]
Thank you lol

**Comment by justcla** [comment]
😁 No problem! I hope those IntelliJ key bindings work nicely for you.
I'll look into why those Format shortcuts didn't work.

**Comment by justcla** [comment]
FYI - I updated the shortcuts for RemoveAndSort (Optimise imports). The FormatDocument is also working.
Check the [latest release](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotKeys) v4.2.1

**Comment by andrew121410** [comment]
Awesome! Thank you!, once again.
