### ISSUE TITLE
VS2017 resharper idea "ctrl+y" removes line instead the "Redo"

### ISSUE THREAD

**Issue by strrranger** [justcla/KeyBindings#5]

**Comment by justcla** [comment]
Hi Strranger. Thanks for raising issues on the ReSharper mappings. I made a best guess at the R# IDEA keyboard shortcuts. I used the [published PDF](https://github.com/justcla/KeyBindings/blob/master/KeyboardSchemes/KeymapRefs/ReSharper_DefaultKeymap_IDEAscheme.pdf) and added that on top of the IntelliJ IDEA scheme.
I have since then discovered that many of the R# IDEA shortcuts are different to the IntelliJ IDEA shortcut. (ie. R# IDEA uses VS shortcuts for debugging, not InteliJ shortcuts). This Ctrl+Y must be another one that I incorrectly ported from the IntelliJ mappings.

I am grateful to finally have someone testing the R# IDEA mappings. Please keep the suggestions coming.
Also, feel free to submit a PR with updates to the [R# settings file](https://github.com/justcla/KeyBindings/blob/master/KeyboardSchemes/VSSettings/ReSharper%20for%20IDEA.vssettings).

Thanks

**Comment by justcla** [comment]
Also, need to add the "Redo" shortcut to the IDEA schemes (Ctrl+Shift+Z).

**Comment by justcla** [comment]
I just discovered that VS has been using Ctrl+Shift+Z as a shortcut for Redo since at least VS2015.

**Comment by justcla** [comment]
It looks like this has been taken care of. Ctrl+Y for DeleteLine is no longer part of the ReSharper mapping schemes.
